---
parserOptions:
    ecmaVersion: 2020
    sourceType: module
    ecmaFeatures:
        impliedStrict: true
env:
    node: true
    es6: true
    jest: true
extends:
    - eslint:recommended
    - prettier
