name: master
on:
  push:
    branches:
      - master
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/workflows/setup.yml
      - name: Lint Check
        run: pnpm run lint
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/workflows/setup.yml
      - name: Test
        run: pnpm run test
